spring:
  application:
    name: Shortner

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Raj@9676

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8086